package com.hiberus.headbook.model;
// default package
// Generated Dec 18, 2018 5:12:43 PM by Hibernate Tools 5.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Objects;
import java.util.Set;
import java.util.UUID;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;


/**
 * Post generated by hbm2java
 */
@Entity
public class Post implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6105586840732412134L;
	
	private UUID id;
	@NotNull
	private Usuario usuario;
	@NotNull
	private Date date;
	@NotNull
	private String title;
	@NotNull
	private String content;
	private String mostrarPost;
	private int countLikes;
	private Set<Likes> likes = new HashSet<Likes>(0);

	
	public Post() {
	}

	public Post(UUID id) {
		this.id = id;
	}

	public Post(UUID id, Usuario user, Date date, String title, String content) {
		this.id = id;
		this.usuario = user;
		this.date = date;
		this.title = title;
		this.content = content;
	}

	@Id
	@GeneratedValue
	public UUID getId() {
		return this.id;
	}

	public void setId(UUID id) {
		this.id = id;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Transient
	public String getMostrarPost() {
		if (content.length()>=50)
			mostrarPost=content.substring(0, 50);
		else mostrarPost=content;
		return mostrarPost;
	}

	public void setMostrarPost(String mostrarPost) {
		this.mostrarPost = mostrarPost;
	}
	
	@Transient
	public int getCountLikes() {
		countLikes=likes.size();
		return countLikes;
	}

	public void setCountLikes(int countLikes) {
		this.countLikes = countLikes;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario")
	public Usuario getUsuario() {
		return usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	
	@OneToMany(mappedBy="post", fetch = FetchType.LAZY,
	        cascade = CascadeType.ALL,
	        orphanRemoval = true)
	public Set<Likes> getLikes() {
		return likes;
	}

	public void setLikes(Set<Likes> likes) {
		this.likes = likes;
	}
	
	
	@Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Post)) return false;
        Post that = (Post) o;
        return Objects.equals(getId(), that.getId());
    }
 
    @Override
    public int hashCode() {
        return Objects.hash(getId());
    }

	public Post orElseThrow(Object object) {
		// TODO Auto-generated method stub
		return null;
	}

	
}
